//  This file should be automatically generated by the configuration phase,
//  based on a file containing known devices that do not need the rcp check,
//  togethr with any extra devices that are found attached to the system on
//  which the configuration is executed.
//  The array needs to be ordered according to strcmp rules.
static const char* devicesQuasiQuoRem[] = 
{
  "GeForce GTX 1080",
  "GeForce GTX 980 Ti",
  "Tesla V100-SXM2-16GB",
};

